# Generated by Django 4.2.7 on 2023-11-05 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron_app', '0002_alter_cronexecutionlog_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronexecutionlog',
            name='execution_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 20, 46, 53, 626102)),
        ),
    ]
