# Generated by Django 4.2.7 on 2023-11-06 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cron_app', '0003_alter_cronexecutionlog_execution_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CronExecutionLog',
        ),
    ]
